### PR TITLE
71 fix all warning messages and imports issues

### LINKED ISSUE #71: Fix All Warning Messages and Imports Issues
**Fix All Warning Messages and  Imports Issues**

- [x] Review the console for any warning messages related to image performance or other issues.
- [x] Address and fix all warning messages to ensure a smooth user experience.

### PR DESCRIPTION
**Pull request by riadhmouamnia**
## Fix All Warning Messages and Imports

fixes #71 

**Description:**
I've addressed several key improvements in this PR to enhance the overall project quality. Here's a breakdown of the changes made:

1. **Console Warning Messages:** I meticulously reviewed the console for any warning messages, particularly those related to image performance or other issues. I'm pleased to report that all warning messages have been identified and fixed, ensuring a smoother user experience.

2. **Dynamic Data on Landing Page:** Static data on the landing page has been replaced with dynamic data fetched in real time. This adjustment not only provides users with the latest information but also enhances the overall functionality and user experience.

3. **Test File Updates:** I've updated the test files to align with the recent code changes, maintaining thorough test coverage to ensure project stability.

4. **Static Path Issues:** Some issues related to static paths in the blog details page have been resolved, contributing to a more seamless browsing experience.

5. **Next.js Update:** I've upgraded Next.js to version 13.5.5 to benefit from the latest features and improvements.

6. **i18next Configuration:** I've made necessary modifications to the i18next configuration to prevent potential deployment issues. While these changes should help ensure a smooth deployment, we will remain vigilant for any errors that may arise during the deployment process.

These updates collectively enhance the performance, stability, and user experience of the project. Your feedback and suggestions are highly encouraged as we continue to improve and refine our project.

**⚠️PS:** Don't forget to run `npm install` again to update the next js version before you run the `npm run dev`

Please review these changes, and your feedback and insights will be greatly appreciated. Let's work together to maintain the project's quality and reliability.

@riadhmouamnia 

# Related Issue

- Resolve #71

### CODE REVIEW

**Review by rahemSorour — APPROVED** [review]
Great work on this PR! these changes significantly enhance the project's quality and reliability. Well done!

**Review by farouk26 — APPROVED** [review]
This is an excellent contribution to the project. Your attention to detail and the various enhancements you've made will certainly have a positive impact. Resolving console warning messages, introducing dynamic data on the landing page, and ensuring that our test suite remains up to date are all significant steps in the right direction.

The updates related to static paths and the Next.js upgrade are valuable for a smoother browsing experience and taking advantage of the latest features. I appreciate your proactive approach in addressing potential deployment issues with the **i18next configuration**.

A friendly reminder to all team members: After merging this PR, please make sure to run `npm install `again to **update Next.js** before starting `npm run dev`.

Please proceed with the merge once you've addressed any feedback from other team members.

**Review by farouk26 — CHANGES_REQUESTED** [review]
Following up with @liliumorion i'm facing the same issues as well

**Comment by riadhmouamnia** [comment]
> In my case, I can still get one warning as shown below:
> 
> image

Can you tell me on which page did you see this warning?

**Review by farouk26 — APPROVED** [review]

**Pull request merged**
